# Generated by Django 3.1.3 on 2020-12-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edamam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edamam_id', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('category_label', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=70, unique=True)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_code', models.CharField(max_length=15)),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Qualifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FoodNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edamam.food')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edamam.nutrient')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edamam.unit')),
            ],
        ),
        migrations.CreateModel(
            name='FoodMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='weight of the measure in grams')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edamam.food')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edamam.measure')),
                ('qualifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edamam.qualifier')),
            ],
        ),
    ]
