# Generated by Django 3.1.5 on 2021-01-09 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edamam', '0002_food_foodmeasure_foodnutrient_measure_nutrient_qualifier_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodnutrient',
            old_name='quantity',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edamam.food'),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edamam.nutrient'),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edamam.unit'),
        ),
    ]
